export {default as SignUp} from './SignUp';
export {default as Login} from './Login';
export {default as Home} from './Home';
export {default as Arts} from './Arts';
export {default as Restaurants} from './Restaurants';
export {default as Event} from './Event';
export {default as Routes} from './Routes';
export {default as Navbar} from './Navbar';
export {default as SearchBar} from './SearchBar';